apiVersion: v1
kind: Service
metadata:
  name: service-user-deployment-svc
spec:
  type: NodePort
  selector:
    app: service-user-deployment
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 9090